development:
  adapter: mysql2
  encoding: utf8
  database: xmca_development
  pool: 5
  username: 
  password: 
  socket: /private/tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: xmca_test
  pool: 5
  username: 
  password: 
  socket: /private/tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: xmca_production
  pool: 5
  username: 
  password: 
  socket: /private/tmp/mysql.sock

